# Generated by Django 4.2.6 on 2023-11-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newsletter_newslettercategory_newslettermedia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitespecificationsdetailmodel',
            name='specification_of',
        ),
        migrations.DeleteModel(
            name='SiteSpecificationModel',
        ),
        migrations.DeleteModel(
            name='SiteSpecificationsDetailModel',
        ),
    ]
